[tool.black]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = [
  "no-else-break",
  "no-else-continue",
  "no-else-return",
  "too-many-instance-attributes",
  "too-many-lines",
  "too-many-public-methods",
  "wrong-import-order",
]
