# testing
[tool.pytest.ini_options]
asyncio_mode = "auto"

# linters
[tool.black]
line-length = 120

[tool.pylint.format]
max-line-length = 120

[tool.pylint."messages control"]
disable = [
  "no-else-break",
  "no-else-continue",
  "no-else-return",
  "too-many-instance-attributes",
  "too-many-lines",
  "too-many-public-methods",
  "wrong-import-order",
]

[tool.flake8]
max-line-length = 120
extend-ignore = [
    "D107",
    # https://black.readthedocs.io/en/stable/faq.html#why-are-flake8-s-e203-and-w503-violated
    "E203",
    # https://github.com/PyCQA/pydocstyle/issues/627
    "D202",
]
